server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  datasource:
    username: postgres
    password: 1
    url: jdbc:postgresql://localhost:5432/e_commerce

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    protocol: smtp
    username: dat
    password: 1
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
          ssl:
            trust: "*"
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000