server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8090

spring:
  datasource:
    username: postgres
    password: 1
    url: jdbc:postgresql://localhost:5432/e_commerce

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: dat
    password: 1

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enabled: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000